catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.product_list,name='product_list'),
    url(r'^categoria/(?P<slug>[\w_-]+)/$',views.category,name='category'),
    #url /produtos/design por exemplo
    url(r'^produtos/(?P<slug>[\w_-]+)/$',views.product,name='product'),
]

checkout/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.add_cart,
        name='add_cart'
	),
   url(r'^carrinho/$', views.cart_item, name='cart_item'),
   url(r'^finalizando/$', views.checkout, name='checkout')
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from core import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^contato/$',views.contact,name='contact'),
    url(r'^entrar/$',login,{'template_name':'login.html'},name='login'),
    url(r'^sair/$',logout,{'next_page':'index'},name='logout'),
    url(r'^catalogo/',include('catalog.urls',namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/',include('checkout.urls',namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

checkout/models.py
from django.db import models
from django.conf import settings

# Create your models here.



#não colocar logica na view e sim criar os metodos do modelo como manager
class CartItemManager(models.Manager):

	def add_item(self,cart_key,product):
		if self.filter(cart_key=cart_key, product=product).exists():
			created = False
			cart_item = self.get(cart_key=cart_key, product=product)
			cart_item.quantity = cart_item.quantity + 1
			cart_item.save()
		else:
		    created = True
		    cart_item = CartItem.objects.create(
		        cart_key=cart_key, product=product, price=product.price
		    )
		return cart_item, created

class CartItem(models.Model):
	#identificador do carrinho de compras
	cart_key = models.CharField('Chave do Carrinho',max_length=40,db_index=True)
	product = models.ForeignKey('catalog.Product',verbose_name='Produto')
	quantity = models.PositiveIntegerField('Quantidade',default=1)
	price = models.DecimalField('Preço',decimal_places=2,max_digits=8)

	#sobrescrita do manager
	objects = CartItemManager()

	class Meta:
		verbose_name = 'Item do Carrinho'
		verbose_name_plural = 'Itens do Carrinho'
		#no carrinho não sera possivel ter dois produtos no mesmo carrinho usar unique_together para criar os indices
		unique_together = (('cart_key','product'),)

	def __str__(self):
		return '{} [{}]'.format(self.product,self.quantity)


class OrderManager(models.Manager):

	def create_order(self,user,cart_itens):
		#cria o pedido
		order = self.create(user = user)
		for cart_item in cart_itens:
			order_item = OrderItem.objects.create(order = order,product=cart_item.product,quantity=cart_item.quantity,price=cart_item.price)
		return order

#pedido após finalizar o carrinho de compra
class Order(models.Model):

	PAYMENT_CHOICES = (
		('pagseguro','PagSeguro'),
		('deposito','Deposito'),
		('paypal','Paypal'),
	)

	STATUS_CHOICES = (
		(0,'Aguardando Pagamento'),
		(1,'Concluida'),
		(2,'Cancelada'),
	)

	user = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name = "Usuário")
	status = models.IntegerField('Situação',choices=STATUS_CHOICES,default=0,blank=True)
	payment_option = models.CharField('Opção pagamento',choices = PAYMENT_CHOICES,max_length=20,default='deposito')
	created = models.DateTimeField('Criado em',auto_now_add=True)
	modified = models.DateTimeField('Atualizado em',auto_now=True)

	objects = OrderManager()

	class Meta:
		verbose_name = 'Pedido'
		verbose_name_plural = 'Pedidos'

	def __str__(self):
		return 'Pedido #{}'.format(self.pk)

#itens do pedido
class OrderItem(models.Model):

	#related_name serve para referenciar a instancia de Order...Order.itens
	order = models.ForeignKey(Order,verbose_name='Pedido',related_name='itens')
	product = models.ForeignKey('catalog.Product',verbose_name='Produto')
	quantity = models.PositiveIntegerField('Quantidade',default=1)
	price = models.DecimalField('Preço',decimal_places=2,max_digits=8)

	class Meta:
		verbose_name = 'Item do Pedido'
		verbose_name_plural = 'Itens do Pedido'

	def __str__(self):
		return 'Pedido:{}, Produto:{}'.format(self.order,self.product)
	

def post_save_cart_item(instance,**kwargs):
	if instance.quantity < 1:
		instance.delete()


#utilizando o signals que serve como gatilho nesse exemplo se a quantidade for zero o item vai ser removido
models.signals.post_save.connect(post_save_cart_item,sender=CartItem,dispatch_uid='post_save_cart_item')

checkout/views.py
# coding=utf-8

from django.shortcuts import get_object_or_404,redirect
from django.views.generic import RedirectView, TemplateView
from django.forms import modelformset_factory
from django.contrib import messages
from django.core.urlresolvers import reverse
#utilizado em views baseada em classe
from django.contrib.auth.mixins import LoginRequiredMixin
#usado em view baseada em funcoes
from django.contrib.auth.decorators import login_required

from catalog.models import Product

from .models import CartItem,Order


class CreateCartItemView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CartItem.objects.add_item(
            self.request.session.session_key, product
        )
        if created:
            messages.success(self.request, 'Produto adicionado com sucesso')
        else:
            messages.success(self.request, 'Produto atualizado com sucesso')
        return reverse('checkout:cart_item')


class CartItemView(LoginRequiredMixin,TemplateView):

    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(
            CartItem, fields=('quantity',), can_delete=True, extra=0
        )
        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key)
                )
            else:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())
        return formset

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context

    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)

class CheckoutView(LoginRequiredMixin,TemplateView):

	template_name = 'checkout/checkout.html'
	def get(self,request,*args,**kwargs):
		session_key = request.session.session_key
		if session_key and CartItem.objects.filter(cart_key = session_key).exists():
			cart_itens = CartItem.objects.filter(cart_key = session_key)
			order = Order.objects.create_order(user=request.user,cart_itens = cart_itens)
		else:
			messages.info(request,'Não há itens no carrinho de compras')
			return redirect('checkout:cart_item')
		return super(CheckoutView,self).get(request,*args,**kwargs)


	
add_cart = CreateCartItemView.as_view()
cart_item = CartItemView.as_view()
checkout = CheckoutView.as_view()

checkout/templates/checkout/cart.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
Carrinho de Compras
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li class="active">Carrinho de Compras</li>
</ol>
<div class="page-header">
    <h1>Carrinho de Compras</h1>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form class="" action="" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table table-bordered">
                <thead>
                    <th>
                        ID
                    </th>
                    <th>
                        Nome
                    </th>
                    <th>
                        Preço
                    </th>
                    <th style="width: 10%;">
                        Quantidade
                    </th>
                    <th>

                    </th>
                </thead>
                <tbody>
                    {% for form in formset %}
                        <tr>
                            <td>
                                {{ form.instance.product.pk }}
                            </td>
                            <td>
                                {{ form.instance.product }}
                            </td>
                            <td>
                                R$ {{ form.instance.price|floatformat:"2" }}
                            </td>
                            <td>
                                {% render_field form.quantity class="form-control" %}
                            </td>
                            <td class="text-center">
                                <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="btn btn-danger btn-sm">remover</button>
                                {{ form.id }}
                            </td>
                        </tr>
                    {% empty %}
                        Carrinho vazio
                    {% endfor %}
                </tbody>
            </table>
            <p class="text-right">
                <a href="{% url 'catalog:product_list' %}" class="pull-left btn btn-default">Continuar Compras</a>
                <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
                <a href="{% url 'checkout:checkout'%}" class="btn btn-success">Finalizar Compra</a>
            </p>
        </form>
    </div>
</div>
{% endblock %}

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
Finalização da Compra
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho <span class="glyphicon glyphicon-shopping-cart"></span></a></li>
  <li class="active">Finalização da Compra</li>
</ol>
<div class="page-header">
    <h1>Finalização da Compra</h1>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-success">
            Seu pedido foi realizado com sucesso, para realizar o pagamento faça o depósito na seguinte conta:
        </div>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
    </div>
</div>
{% endblock %}