accounts/urls.py
from django.conf.urls import url,include
from accounts import views

urlpatterns = [
    url(r'^registro/$',views.register,name='register'),
    url(r'^atualizar-dados/$',views.update_user,name='update_user'),
    url(r'^alterar-senha/$',views.password_change,name='password_change'),
    url(r'^usuarios/$',views.userlist,name='userlist'),
    url(r'^$',views.index,name='index'),
]

catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.product_list,name='product_list'),
    url(r'^categoria/(?P<slug>[\w_-]+)/$',views.category,name='category'),
    #url /produtos/design por exemplo
    url(r'^produtos/(?P<slug>[\w_-]+)/$',views.product,name='product'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from core import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^contato/$',views.contact,name='contact'),
    url(r'^entrar/$',login,{'template_name':'login.html'},name='login'),
    url(r'^sair/$',logout,{'next_page':'index'},name='logout'),
    url(r'^catalogo/',include('catalog.urls',namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/',include('checkout.urls',namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

accounts/models.py
import re
from django.core import validators
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,UserManager,PermissionsMixin

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms



class UserAdminCreationForm(UserCreationForm):

    #sobrescrever a classe meta para adicionar novos campos

    class Meta:
        model = User
        fields = ['username','name','email']

class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username','email','name','is_active','is_staff']

accounts/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,CreateView,ListView,UpdateView,FormView
from .models import User
from django.contrib.messages.views import SuccessMessageMixin
#utilizado em views baseada em classe
from django.contrib.auth.mixins import LoginRequiredMixin
#usado em view baseada em funcoes
from django.contrib.auth.decorators import login_required
from .forms import UserAdminCreationForm
from django.core.urlresolvers import reverse_lazy,reverse
from django.contrib.auth.forms import PasswordChangeForm




# Create your views here.
class IndexView(LoginRequiredMixin,TemplateView):
    template_name = 'accounts/index.html'

index = IndexView.as_view()

class UpdateUserView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name','email']
    success_message = 'Usuario atualizado com sucesso'
    #success_url = reverse_lazy()

    #sobrescrever o metodo get_object pois o usuario a ser atualizado é o logado
    def get_object(self):
        return self.request.user

    #pode sobrescrever o metodo ou atribuir ao success_url
    def get_success_url(self):
        view_name = 'accounts:index'
        return reverse_lazy(view_name)

update_user = UpdateUserView.as_view()

#utilizando o form do django
class UpdatePasswordView(LoginRequiredMixin,FormView):
    template_name = 'accounts/password_change.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('accounts:index')

    #insere o objeto no argumento para instanciar o form
    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView,self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

password_change = UpdatePasswordView.as_view()


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')

register = RegisterView.as_view()

class UsersListView(ListView):

    model = User
    template_name = 'accounts/userlist.html'
    context_object_name = 'users'


userlist = UsersListView.as_view()

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha Conta{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="#">Início</a></li>
  <li class="active">Minha Conta</li>
</ol>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
          <a href="#" class="list-group-item active">Minha Conta</a>
          <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
          <a href="{% url 'accounts:password_change' %}" class="list-group-item">Alterar Senha</a>
        </div>
    </div>
    <div class="col-md-8">
      {% block accounts_container %}
          <h2 class="text-center">Bem vindo {{ user }}</h2>
      {% endblock %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Registro | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        {% if success_message %}
          <div class="alert alert-danger">
              {{success_message}}
          </div>
        {% endif %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-2 control-label">{{ field.label }}</label>
              <div class="col-md-7">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

accounts/templates/accounts/userlist.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Lista de usuarios | {{ block.super }}{% endblock %}

{% block container %}
<div class="page-header">
  <h3>Produtos</h3>
</div>
  <div class="row">
      <div class="col-sm-12 col-md-12">
          <div class="table-responsive">
              <table class="table table-hover table-bordered">
                <thead>
                  <th>Nome</th>
                  <th>Email</th>
                  <th>Ativo</th>
                  <th>Editar</th>
                </thead>
                <tbody>
                  {% for user in users  %}
                      <tr>
                        <td>{{ user.name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.is_active }}</td>
                        <td>
                          <a href="#">
                            <span class="glyphicon glyphicon-pencil"></span>
                          </a>
                        </td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
      </div>
{% endblock %}