accounts/urls.py
from django.conf.urls import url,include
from accounts import views

urlpatterns = [
    url(r'^registro/$',views.register,name='register'),
    url(r'^atualizar-dados/$',views.update_user,name='update_user'),
    url(r'^alterar-senha/$',views.password_change,name='password_change'),
    url(r'^usuarios/$',views.userlist,name='userlist'),
    url(r'^$',views.index,name='index'),
]

catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.product_list,name='product_list'),
    url(r'^categoria/(?P<slug>[\w_-]+)/$',views.category,name='category'),
    #url /produtos/design por exemplo
    url(r'^produtos/(?P<slug>[\w_-]+)/$',views.product,name='product'),
]

checkout/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.add_cart,
        name='add_cart'
	),
   url(r'^carrinho/$', views.cart_item, name='cart_item'),
   url(r'^finalizando/$', views.checkout, name='checkout')
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from core import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^contato/$',views.contact,name='contact'),
    url(r'^entrar/$',login,{'template_name':'login.html'},name='login'),
    url(r'^sair/$',logout,{'next_page':'index'},name='logout'),
    url(r'^catalogo/',include('catalog.urls',namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/',include('checkout.urls',namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail


class ContactForm(forms.Form):
    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='Email')
    message = forms.CharField(label='Mensagem',widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome:{0}\nEmail:{1}\n{2}'.format(name,email,message)
        #enviando email no console
        send_mail('Contato Django E-commerce',message,settings.DEFAULT_FROM_EMAIL,[settings.DEFAULT_FROM_EMAIL])

    '''

    #mudar aparencia do form adicionando classe do bootstrap
    usar o widget_tweaks no template
    def __init__(self,*args,**kwargs):
        super(ContactForm,self).__init__(*args,**kwargs)
        #atribuindo ao widget no atributo classe o form-control do bootstrap
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['class'] = 'form-control'
    '''

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from catalog.models import Category
from .forms import ContactForm
from django.contrib import messages
#classe principal generica
from django.views.generic import View,TemplateView,CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy

#model user do django
User = get_user_model()

# Create your views here.
"""função que recebe uma request e devolve HttpResponse"""
class IndexView(TemplateView):
    # metodo da view
    template_name = 'index.html'
    #metodo para adicionar o contexto
    def get_context_data(self,**kwargs):
        context = super(IndexView,self).get_context_data(**kwargs)
        context['description'] = 'Testando o foorloop do Django','e aprendendo tambem sobre o','if e foorloop que contem','o controle do laço'
        context['title'] = 'Django E-commerce'
        return context

index = IndexView.as_view()

"""
 a classe de erro do bootstrap se chama danger e a do message se chama alert então
 é necessario sobrescrever as tags do message trocando de error para danger ver settings
"""
def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    #sempre testar se form é valido
    if form.is_valid():
        form.send_mail()
        messages.success(request,'Operação realizado com sucesso')
        form = ContactForm()
    else:
        messages.error(request,'Ocorreu um erro')
    context = {
        'form': form,
    }
    return render(request,'contact.html',context)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Django E-Commerce{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/css/custom.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/css/extra.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
				{% for category in categories %}
				<li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
				{% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
			<li><a href="{% url 'logout' %}">Bem vindo {{ user }} <span class="glyphicon glyphicon-log-out"></span></a></li>
			{% else %}
			<li><a href="{% url 'login' %}">Entrar&nbsp<span class="glyphicon glyphicon-log-in"></span></a></li>
			<li><a href="{% url 'accounts:register' %}">Registro</a></li>
			{% endif %}
			<li><a href="{% url 'checkout:cart_item' %}">Carrinho&nbsp<span class="glyphicon glyphicon-shopping-cart"></span></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container margin-top">
		{% block messages %}
		{% for message in messages %}
		<div id="msg" class="alert alert-{{ message.tags }}">
			{{ message }}
		</div>
		{% endfor %}
		{% endblock %}
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript">
    	$(document).ready(function() {
			setTimeout("$('#msg').hide()", 6000);
			});
    </script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}
    {{ block.super}} Contato
{% endblock %}

{% block container %}
<div class="page-header">
<h1>Fale conosco</h1>
<form class="form-horizontal" action="" method="post">
  {% csrf_token %}
    <fieldset>
        {% for campo  in form  %}
          <div class="form-group{% if campo.errors%}has-error{% endif %}">
            <label for="{{ campo.auto_id }}" class="col-md-3 control-label">{{ campo.label }}</label>
            <div class="col-md-9">
              {% render_field campo class='form-control' %}
              {% for erro in campo.errors %}
                <span class="help-block">{{ erro }}</span>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Enviar</button>
          </div>
        </div>
    </fieldset>
</form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% block container %}
	<div class="jumbotron page-header">
		<h1>{{title}}</h1>
		<p>
			{% for item in description %}
				{{item}}
			{% endfor %}
		</p>
		<p><a class="btn btn-primary">Saiba mais</a></p>
	</div>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
          <ul class="pagination">
              {% for page in paginator.page_range %}
              <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
              {% endfor %}
          </ul>
        </nav>
    </div>
</div>