catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.product_list,name='product_list'),
    url(r'^categoria/(?P<slug>[\w_-]+)/$',views.category,name='category'),
    #url /produtos/design por exemplo
    url(r'^produtos/(?P<slug>[\w_-]+)/$',views.product,name='product'),
]

checkout/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.add_cart,
        name='add_cart'
	),
   url(r'^carrinho/$', views.cart_item, name='cart_item'),
   url(r'^finalizando/$', views.checkout, name='checkout')
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from core import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^contato/$',views.contact,name='contact'),
    url(r'^entrar/$',login,{'template_name':'login.html'},name='login'),
    url(r'^sair/$',logout,{'next_page':'index'},name='logout'),
    url(r'^catalogo/',include('catalog.urls',namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/',include('checkout.urls',namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(verbose_name='Nome',max_length=100)
    slug = models.SlugField('Identificador',max_length=100)
    created = models.DateTimeField('Criado em',auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em',auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        '''se a ordem for decres colocar - na frente do campo'''
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category',kwargs={'slug':self.slug})

class Product(models.Model):
    name = models.CharField(verbose_name='Nome',max_length=100)
    slug = models.SlugField('Identificador',max_length=100)
    '''um produto tem varias categorias'''
    category = models.ForeignKey('catalog.Category',verbose_name='Categoria')
    description = models.TextField('Descrição',blank=True)
    price = models.DecimalField('Preço',decimal_places=2,max_digits=8)
    created = models.DateTimeField('Criado em',auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em',auto_now=True)
    image = models.ImageField(
            upload_to='catalog/images', verbose_name='Imagem',
            null=True, blank=True
    )

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        '''se a ordem for decres colocar - na frente do campo'''
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product',kwargs={'slug':self.slug})

catalog/views.py
# codding=utf-8
from django.shortcuts import render,get_object_or_404
from .models import Product,Category
from django.views import generic
# Create your views here.


class ProductListView(generic.ListView):
    template_name = 'catalog/product_list.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 5



product_list = ProductListView.as_view()

class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self,*args, **kwargs):
        context = super(CategoryListView,self).get_context_data(*args, **kwargs)
        context['current_category'] = get_object_or_404(Category,slug=self.kwargs['slug'])
        context['product_list'] = self.get_queryset
        return context

category = CategoryListView.as_view()

def product(request,slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product':product,
    }
    return render(request,'catalog/product.html',context)

catalog/templates/catalog/_product.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href="{{product.get_absolute_url}}" class="thumbnail">
            {% if product.image %}
                {{ product.image.url }}
            {% else %}
                <img src="http://placehold.it/350x250" alt="" />
            {% endif %}
        </a>
        <div class="caption">
            <h3>{{product.name}}</h3>
            <p>{{product.description}}</p>
            <p>Preço {{product.price}}</p>
            <p>Categoria {{product.category}}</p>
            <p><a href="{{product.get_absolute_url}}" class="btn btn-success" role="button">Detalhes</a> <a href="{% url 'checkout:add_cart' product.slug %}" class="btn btn-default" role="button">Adicionar</a></p>
        </div>
    </div>
</div>

catalog/templates/catalog/category.html
{% extends "base.html" %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>{{ current_category }}</h1>
</div>
<div class="row">
    {% for product in product_list %}
        <!-- utilizar o include qd a logica for a mesma para outra pagina -->
       {% include "catalog/_product.html" %}   
    {% empty %}
          Nenhum produto encontrado
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block title  %}
    {{ block.super }} {{product}}
{% endblock %}

{% block container %}
<div class="page-header">
<h1>{{product}}</h1>
</div>
<div class="row">
	<div class="col-sm-4">
	    <a href="#" class="thumbnail">
	        {% if product.image %}
                {{ product.image.url }}
            {% else %}
                <img src="http://placehold.it/350x250" alt="" />
            {% endif %}
	    </a>
	</div>
	<div class="col-sm-8">
	    {{product.description|linebreaks}}
	    <a href="{% url 'checkout:add_cart' product.slug %}" class="btn btn-default" role="button">Adicionar</a></p>
	</div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}
{% load pagination %}

{% block title %}
    {{ block.super }} Lista de Produtos
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Produtos</h1>
</div>
<div class="row">
    {% for product in products  %}
        {% include "catalog/_product.html" %}
    {% endfor %}
  </div>
  {% pagination request paginator page_obj %}
{% endblock %}